# Generated by Django 4.0.1 on 2022-01-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeP', models.CharField(max_length=255)),
                ('urlP', models.TextField()),
                ('descP', models.TextField()),
                ('precoP', models.FloatField()),
                ('qunati', models.IntegerField()),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
